org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home

enabledPlatforms=fabric,neoforge

version=1.16.6
group=earth.terrarium.adastra

minecraftVersion=1.21.1
mixinExtrasVersion=0.4.1
parchmentVersion=2024.07.28

modMenuVersion=11.0.3
reiVersion=16.0.788
jeiVersion=19.21.0.247

patchouliVersion=81
shimmerVersion=0.2.3

athenaVersion=4.0.3
cadmusVersion=2.0.0-alpha.5
argonautsVersion=2.0.0-alpha.5

resourcefulLibVersion=3.0.12
resourcefulConfigVersion=3.0.11
commonStorageLibVersion=0.0.7